### ISSUE TITLE
Feature request: add support for self hosted instance of Plausible

### ISSUE THREAD

**Issue by thiemo** [spekulatius/vuepress-plugin-plausible#2]
Hi, I'd like to propose a feature request to support self hosted instances of Plausible. To accomplish this the URI of the self hosted script should be a variable to be set in `.vuepress/config.js`

**Comment by spekulatius** [comment]
Hey @thiemo ,

that's a good idea, are you interested in preparing a PR?

Cheers,
Peter

**Comment by woss** [comment]
i  don't know why this is in the readme.md when it is not implemented.

Now you have a PR that implements this, i would appreciate if you could publish new version so i don't have to use my PR

<img width="644" alt="image" src="https://user-images.githubusercontent.com/80440/191971512-79b9d714-93da-4744-b6d4-6bd8fc04a4d8.png">

**Comment by woss** [comment]
ha! https://github.com/spekulatius/vuepress-plugin-plausible/commit/3cc33048dd14f82b93702c43bcbca0194467815d you never published the changes!

**Comment by spekulatius** [comment]
Hey @woss 

it is in master right? Can you confirm it works as expected?

Cheers,
Peter

**Comment by woss** [comment]
if you refer to your code that is in the master then no it doesn't. the simplest way to see is to install the latest version from the npm

**Comment by spekulatius** [comment]
Yeah, let's keep it simple and keep the existing code.

**Comment by woss** [comment]
i completely agree, but can you publish it then with your code?

**Comment by woss** [comment]
@spekulatius this is the version that's on ipfs https://github.com/spekulatius/vuepress-plugin-plausible/blob/v0.0.3/inject.js you can see that your code is NOT there :)

**Comment by spekulatius** [comment]
Hmm, the separate workflow for publishing is a bit error-prone... :/

I've just tried `npm publish` and it fails with these:

```
11:47 $ npm publish
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/vuepress-plugin-plausible - You cannot publish over the previously published versions: 0.0.3.
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy, or
npm ERR! 403 on a server you do not have access to.
// ...
```

or

```
11:47 $ npm publish --tag v0.0.4
npm ERR! Tag name must not be a valid SemVer range: v0.0.4
```

Any suggestion on how this might be resolved @woss ?

**Comment by woss** [comment]
maybe to remove the `v` from the tag? `v` is not in the spec for the semver

**Comment by spekulatius** [comment]
The previous ones all have a 'v' and it worked. I've also tagged and tried the non-v version and had a the same error - just without 'v' in the error message.

**Comment by woss** [comment]
then i cannot help you. i'll continue using my PR until you publish this.

**Comment by spekulatius** [comment]
Hey @woss 

I figured out the problem. Can you check if it works now? 

Cheers,
Peter

**Comment by woss** [comment]
i am sorry but i cannot. i switched from vuepress  to docusaurus. if it's in the npm and resolved and downloaded it will work 100% :)
